version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'springdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'asijee'
      MYSQL_ROOT_PASSWORD: 'longa1986'
    ports:
      - '3306:3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'